apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: 601311288054.dkr.ecr.us-east-1.amazonaws.com/argocd-test:latest
          name: nginx
          ports:
            - containerPort: 80
